/**
 * Durandal 2.0.1 Copyright (c) 2012 Blue Spire Consulting, Inc. All Rights Reserved.
 * Available via the MIT license.
 * see: http://durandaljs.com or https://github.com/BlueSpire/Durandal for details.
 */

define(["durandal/system","durandal/app","durandal/composition","durandal/activator","durandal/viewEngine","jquery","knockout"],function(e,t,n,r,i,s,o){function c(t){return e.defer(function(n){e.isString(t)?e.acquire(t).then(function(t){n.resolve(e.resolveObject(t))}).fail(function(n){e.error("Failed to load dialog module ("+t+"). Details: "+n.message)}):n.resolve(t)}).promise()}var u={},a=0,f,l=function(e,t,n){this.message=e,this.title=t||l.defaultTitle,this.options=n||l.defaultOptions};return l.prototype.selectOption=function(e){f.close(this,e)},l.prototype.getView=function(){return i.processMarkup(l.defaultViewMarkup)},l.setViewUrl=function(e){delete l.prototype.getView,l.prototype.viewUrl=e},l.defaultTitle=t.title||"Application",l.defaultOptions=["Ok"],l.defaultViewMarkup=['<div data-view="plugins/messageBox" class="messageBox">','<div class="modal-header">','<h3 data-bind="text: title"></h3>',"</div>",'<div class="modal-body">','<p class="message" data-bind="text: message"></p>',"</div>"
,'<div class="modal-footer" data-bind="foreach: options">','<button class="btn" data-bind="click: function () { $parent.selectOption($data); }, text: $data, css: { \'btn-primary\': $index() == 0, autofocus: $index() == 0 }"></button>',"</div>","</div>"].join("\n"),f={MessageBox:l,currentZIndex:1050,getNextZIndex:function(){return++this.currentZIndex},isOpen:function(){return a>0},getContext:function(e){return u[e||"default"]},addContext:function(e,t){t.name=e,u[e]=t;var n="show"+e.substr(0,1).toUpperCase()+e.substr(1);this[n]=function(t,n){return this.show(t,n,e)}},createCompositionSettings:function(e,t){var n={model:e,activate:!1,transition:!1};return t.attached&&(n.attached=t.attached),t.compositionComplete&&(n.compositionComplete=t.compositionComplete),n},getDialog:function(e){return e?e.__dialog__:undefined},close:function(e){var t=this.getDialog(e);if(t){var n=Array.prototype.slice.call(arguments,1);t.close.apply(t,n)}},show:function(t,i,s){var o=this,f=u[s||"default"];return e.defer
(function(e){c(t).then(function(t){var s=r.create();s.activateItem(t,i).then(function(r){if(r){var i=t.__dialog__={owner:t,context:f,activator:s,close:function(){var n=arguments;s.deactivateItem(t,!0).then(function(r){r&&(a--,f.removeHost(i),delete t.__dialog__,n.length===0?e.resolve():n.length===1?e.resolve(n[0]):e.resolve.apply(e,n))})}};i.settings=o.createCompositionSettings(t,f),f.addHost(i),a++,n.compose(i.host,i.settings)}else e.resolve(!1)})})}).promise()},showMessage:function(t,n,r){return e.isString(this.MessageBox)?f.show(this.MessageBox,[t,n||l.defaultTitle,r||l.defaultOptions]):f.show(new this.MessageBox(t,n,r))},install:function(e){t.showDialog=function(e,t,n){return f.show(e,t,n)},t.showMessage=function(e,t,n){return f.showMessage(e,t,n)},e.messageBox&&(f.MessageBox=e.messageBox),e.messageBoxView&&(f.MessageBox.prototype.getView=function(){return e.messageBoxView})}},f.addContext("default",{blockoutOpacity:.2,removeDelay:200,addHost:function(e){var t=s("body"),n=s('<div class="modalBlockout"></div>'
).css({"z-index":f.getNextZIndex(),opacity:this.blockoutOpacity}).appendTo(t),r=s('<div class="modalHost"></div>').css({"z-index":f.getNextZIndex()}).appendTo(t);e.host=r.get(0),e.blockout=n.get(0);if(!f.isOpen()){e.oldBodyMarginRight=t.css("margin-right"),e.oldInlineMarginRight=t.get(0).style.marginRight;var i=s("html"),o=t.outerWidth(!0),u=i.scrollTop();s("html").css("overflow-y","hidden");var a=s("body").outerWidth(!0);t.css("margin-right",a-o+parseInt(e.oldBodyMarginRight,10)+"px"),i.scrollTop(u)}},removeHost:function(e){s(e.host).css("opacity",0),s(e.blockout).css("opacity",0),setTimeout(function(){o.removeNode(e.host),o.removeNode(e.blockout)},this.removeDelay);if(!f.isOpen()){var t=s("html"),n=t.scrollTop();t.css("overflow-y","").scrollTop(n),e.oldInlineMarginRight?s("body").css("margin-right",e.oldBodyMarginRight):s("body").css("margin-right","")}},attached:function(e){s(e).css("visibility","hidden")},compositionComplete:function(e,t,n){var r=f.getDialog(n.model),i=s(e),o=i.find
("img").filter(function(){var e=s(this);return(!this.style.width||!this.style.height)&&(!e.attr("width")||!e.attr("height"))});i.data("predefinedWidth",i.get(0).style.width);var u=function(){setTimeout(function(){i.data("predefinedWidth")||i.css({width:""});var e=i.outerWidth(!1),t=i.outerHeight(!1),n=s(window).height(),o=Math.min(t,n);i.css({"margin-top":(-o/2).toString()+"px","margin-left":(-e/2).toString()+"px"}),i.data("predefinedWidth")||i.outerWidth(e),t>n?i.css("overflow-y","auto"):i.css("overflow-y",""),s(r.host).css("opacity",1),i.css("visibility","visible"),i.find(".autofocus").first().focus()},1)};u(),o.load(u),i.hasClass("autoclose")&&s(r.blockout).click(function(){r.close()})}}),f});