/**
 * Durandal 2.0.1 Copyright (c) 2012 Blue Spire Consulting, Inc. All Rights Reserved.
 * Available via the MIT license.
 * see: http://durandaljs.com or https://github.com/BlueSpire/Durandal for details.
 */

define(["durandal/system","durandal/binder","knockout"],function(e,t,n){function h(e){var t=e[0];return t==="_"||t==="$"}function p(t){return!!t&&t.nodeType!==undefined&&!!e.isNumber(t.nodeType)}function d(e){if(!e||p(e)||e.ko===n||e.jquery)return!1;var t=i.call(e);return s.indexOf(t)==-1&&e!==!0&&e!==!1}function v(e,t){var n=e.__observable__,r=!0;if(n&&n.__full__)return;n=n||(e.__observable__={}),n.__full__=!0,o.forEach(function(n){e[n]=function(){r=!1;var e=l[n].apply(t,arguments);return r=!0,e}}),u.forEach(function(n){e[n]=function(){r&&t.valueWillMutate();var i=f[n].apply(e,arguments);return r&&t.valueHasMutated(),i}}),a.forEach(function(n){e[n]=function(){for(var i=0,s=arguments.length;i<s;i++)m(arguments[i]);r&&t.valueWillMutate();var o=f[n].apply(e,arguments);return r&&t.valueHasMutated(),o}}),e.splice=function(){for(var n=2,i=arguments.length;n<i;n++)m(arguments[n]);r&&t.valueWillMutate();var s=f.splice.apply(e,arguments);return r&&t.valueHasMutated(),s};for(var i=0,s=e.length;i<
s;i++)m(e[i])}function m(t){var r,i;if(!d(t))return;r=t.__observable__;if(r&&r.__full__)return;r=r||(t.__observable__={}),r.__full__=!0;if(e.isArray(t)){var s=n.observableArray(t);v(t,s)}else for(var o in t){if(h(o))continue;r[o]||(i=t[o],e.isFunction(i)||y(t,o,i))}c&&e.log("Converted",t)}function g(e,t,n){var r;e(t),r=e.peek(),n?r?r.destroyAll||v(r,e):(r=[],e(r),v(r,e)):m(r)}function y(t,r,i){var s,o,u=t.__observable__||(t.__observable__={});i===undefined&&(i=t[r]);if(e.isArray(i))s=n.observableArray(i),v(i,s),o=!0;else if(typeof i=="function"){if(!n.isObservable(i))return null;s=i}else e.isPromise(i)?(s=n.observable(),i.then(function(t){if(e.isArray(t)){var r=n.observableArray(t);v(t,r),t=r}s(t)})):(s=n.observable(i),m(i));return Object.defineProperty(t,r,{configurable:!0,enumerable:!0,get:s,set:n.isWriteableObservable(s)?function(t){t&&e.isPromise(t)?t.then(function(t){g(s,t,e.isArray(t))}):g(s,t,o)}:undefined}),u[r]=s,s}function b(t,r,i){var s={owner:t,deferEvaluation:!0},o;return typeof 
i=="function"?s.read=i:("value"in i&&e.error('For defineProperty, you must not specify a "value" for the property. You must provide a "get" function.'),typeof i.get!="function"&&e.error('For defineProperty, the third parameter must be either an evaluator function, or an options object containing a function called "get".'),s.read=i.get,s.write=i.set),o=n.computed(s),t[r]=o,y(t,r,o)}var r,i=Object.prototype.toString,s=["[object Function]","[object String]","[object Boolean]","[object Number]","[object Date]","[object RegExp]"],o=["remove","removeAll","destroy","destroyAll","replace"],u=["pop","reverse","sort","shift","splice"],a=["push","unshift"],f=Array.prototype,l=n.observableArray.fn,c=!1;return r=function(e,t){var r,i,s;if(!e)return null;r=e.__observable__;if(r){i=r[t];if(i)return i}return s=e[t],n.isObservable(s)?s:y(e,t,s)},r.defineProperty=b,r.convertProperty=y,r.convertObject=m,r.install=function(e){var n=t.binding;t.binding=function(e,t,r){r.applyBindings&&!r.skipConversion&&m(e
),n(e,t)},c=e.logConversion},r});