/**
 * Durandal 2.0.1 Copyright (c) 2012 Blue Spire Consulting, Inc. All Rights Reserved.
 * Available via the MIT license.
 * see: http://durandaljs.com or https://github.com/BlueSpire/Durandal for details.
 */

define(["durandal/system","knockout"],function(e,t){function r(e){return e==undefined&&(e={}),e.closeOnDeactivate||(e.closeOnDeactivate=n.defaults.closeOnDeactivate),e.beforeActivate||(e.beforeActivate=n.defaults.beforeActivate),e.afterDeactivate||(e.afterDeactivate=n.defaults.afterDeactivate),e.affirmations||(e.affirmations=n.defaults.affirmations),e.interpretResponse||(e.interpretResponse=n.defaults.interpretResponse),e.areSameItem||(e.areSameItem=n.defaults.areSameItem),e}function i(t,n,r){return e.isArray(r)?t[n].apply(t,r):t[n](r)}function s(t,n,r,i,s){if(t&&t.deactivate){e.log("Deactivating",t);var o;try{o=t.deactivate(n)}catch(u){e.error(u),i.resolve(!1);return}o&&o.then?o.then(function(){r.afterDeactivate(t,n,s),i.resolve(!0)},function(t){e.log(t),i.resolve(!1)}):(r.afterDeactivate(t,n,s),i.resolve(!0))}else t&&r.afterDeactivate(t,n,s),i.resolve(!0)}function o(t,n,r,s){if(t)if(t.activate){e.log("Activating",t);var o;try{o=i(t,"activate",s)}catch(u){e.error(u),r(!1);return}o&&o.then?
o.then(function(){n(t),r(!0)},function(t){e.log(t),r(!1)}):(n(t),r(!0))}else n(t),r(!0);else r(!0)}function u(t,n,r){return r.lifecycleData=null,e.defer(function(i){if(t&&t.canDeactivate){var s;try{s=t.canDeactivate(n)}catch(o){e.error(o),i.resolve(!1);return}s.then?s.then(function(e){r.lifecycleData=e,i.resolve(r.interpretResponse(e))},function(t){e.error(t),i.resolve(!1)}):(r.lifecycleData=s,i.resolve(r.interpretResponse(s)))}else i.resolve(!0)}).promise()}function a(t,n,r,s){return r.lifecycleData=null,e.defer(function(o){if(t==n()){o.resolve(!0);return}if(t&&t.canActivate){var u;try{u=i(t,"canActivate",s)}catch(a){e.error(a),o.resolve(!1);return}u.then?u.then(function(e){r.lifecycleData=e,o.resolve(r.interpretResponse(e))},function(t){e.error(t),o.resolve(!1)}):(r.lifecycleData=u,o.resolve(r.interpretResponse(u)))}else o.resolve(!0)}).promise()}function f(n,i){var f=t.observable(null),l;i=r(i);var c=t.computed({read:function(){return f()},write:function(e){c.viaSetter=!0,c.activateItem
(e)}});return c.__activator__=!0,c.settings=i,i.activator=c,c.isActivating=t.observable(!1),c.canDeactivateItem=function(e,t){return u(e,t,i)},c.deactivateItem=function(t,n){return e.defer(function(e){c.canDeactivateItem(t,n).then(function(r){r?s(t,n,i,e,f):(c.notifySubscribers(),e.resolve(!1))})}).promise()},c.canActivateItem=function(e,t){return a(e,f,i,t)},c.activateItem=function(t,n){var r=c.viaSetter;return c.viaSetter=!1,e.defer(function(u){if(c.isActivating()){u.resolve(!1);return}c.isActivating(!0);var a=f();if(i.areSameItem(a,t,l,n)){c.isActivating(!1),u.resolve(!0);return}c.canDeactivateItem(a,i.closeOnDeactivate).then(function(h){h?c.canActivateItem(t,n).then(function(h){h?e.defer(function(e){s(a,i.closeOnDeactivate,i,e)}).promise().then(function(){t=i.beforeActivate(t,n),o(t,f,function(e){l=n,c.isActivating(!1),u.resolve(e)},n)}):(r&&c.notifySubscribers(),c.isActivating(!1),u.resolve(!1))}):(r&&c.notifySubscribers(),c.isActivating(!1),u.resolve(!1))})}).promise()},c.canActivate=
function(){var e;return n?(e=n,n=!1):e=c(),c.canActivateItem(e)},c.activate=function(){var e;return n?(e=n,n=!1):e=c(),c.activateItem(e)},c.canDeactivate=function(e){return c.canDeactivateItem(c(),e)},c.deactivate=function(e){return c.deactivateItem(c(),e)},c.includeIn=function(e){e.canActivate=function(){return c.canActivate()},e.activate=function(){return c.activate()},e.canDeactivate=function(e){return c.canDeactivate(e)},e.deactivate=function(e){return c.deactivate(e)}},i.includeIn?c.includeIn(i.includeIn):n&&c.activate(),c.forItems=function(t){i.closeOnDeactivate=!1,i.determineNextItemToActivate=function(e,t){var n=t-1;return n==-1&&e.length>1?e[1]:n>-1&&n<e.length-1?e[n]:null},i.beforeActivate=function(e){var n=c();if(!e)e=i.determineNextItemToActivate(t,n?t.indexOf(n):0);else{var r=t.indexOf(e);r==-1?t.push(e):e=t()[r]}return e},i.afterDeactivate=function(e,n){n&&t.remove(e)};var n=c.canDeactivate;c.canDeactivate=function(r){return r?e.defer(function(e){function s(){for(var t=0;t<
i.length;t++)if(!i[t]){e.resolve(!1);return}e.resolve(!0)}var n=t(),i=[];for(var o=0;o<n.length;o++)c.canDeactivateItem(n[o],r).then(function(e){i.push(e),i.length==n.length&&s()})}).promise():n()};var r=c.deactivate;return c.deactivate=function(n){return n?e.defer(function(e){function o(r){c.deactivateItem(r,n).then(function(){i++,t.remove(r),i==s&&e.resolve()})}var r=t(),i=0,s=r.length;for(var u=0;u<s;u++)o(r[u])}).promise():r()},c},c}var n,l={closeOnDeactivate:!0,affirmations:["yes","ok","true"],interpretResponse:function(n){return e.isObject(n)&&(n=n.can||!1),e.isString(n)?t.utils.arrayIndexOf(this.affirmations,n.toLowerCase())!==-1:n},areSameItem:function(e,t,n,r){return e==t},beforeActivate:function(e){return e},afterDeactivate:function(e,t,n){t&&n&&n(null)}};return n={defaults:l,create:f,isActivator:function(e){return e&&e.__activator__}},n});