/**
 * Durandal 2.0.1 Copyright (c) 2012 Blue Spire Consulting, Inc. All Rights Reserved.
 * Available via the MIT license.
 * see: http://durandaljs.com or https://github.com/BlueSpire/Durandal for details.
 */

define(["require","jquery"],function(e,t){function v(e){var t="[object "+e+"]";o["is"+e]=function(e){return s.call(e)==t}}var n=!1,r=Object.keys,i=Object.prototype.hasOwnProperty,s=Object.prototype.toString,o,u=!1,a=Array.isArray,f=Array.prototype.slice;if(Function.prototype.bind&&(typeof console=="object"||typeof console=="function")&&typeof console.log=="object")try{["log","info","warn","error","assert","dir","clear","profile","profileEnd"].forEach(function(e){console[e]=this.call(console[e],console)},Function.prototype.bind)}catch(l){u=!0}e.on&&e.on("moduleLoaded",function(e,t){o.setModuleId(e,t)}),typeof requirejs!="undefined"&&(requirejs.onResourceLoad=function(e,t,n){o.setModuleId(e.defined[t.id],t.id)});var c=function(){},h=function(){try{if(typeof console!="undefined"&&typeof console.log=="function")if(window.opera){var e=0;while(e<arguments.length)console.log("Item "+(e+1)+": "+arguments[e]),e++}else f.call(arguments).length==1&&typeof f.call(arguments)[0]=="string"?console.log
(f.call(arguments).toString()):console.log.apply(console,f.call(arguments));else(!Function.prototype.bind||u)&&typeof console!="undefined"&&typeof console.log=="object"&&Function.prototype.call.call(console.log,console,f.call(arguments))}catch(t){}},p=function(e){throw e instanceof Error?e:new Error(e)};o={version:"2.0.1",noop:c,getModuleId:function(e){return e?typeof e=="function"?e.prototype.__moduleId__:typeof e=="string"?null:e.__moduleId__:null},setModuleId:function(e,t){if(!e)return;if(typeof e=="function"){e.prototype.__moduleId__=t;return}if(typeof e=="string")return;e.__moduleId__=t},resolveObject:function(e){return o.isFunction(e)?new e:e},debug:function(e){return arguments.length==1&&(n=e,n?(this.log=h,this.error=p,this.log("Debug:Enabled")):(this.log("Debug:Disabled"),this.log=c,this.error=c)),n},log:c,error:c,assert:function(e,t){e||o.error(new Error(t||"Assert:Failed"))},defer:function(e){return t.Deferred(e)},guid:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace
(/[xy]/g,function(e){var t=Math.random()*16|0,n=e=="x"?t:t&3|8;return n.toString(16)})},acquire:function(){var t,n=arguments[0],r=!1;return o.isArray(n)?(t=n,r=!0):t=f.call(arguments,0),this.defer(function(n){e(t,function(){var e=arguments;setTimeout(function(){e.length>1||r?n.resolve(f.call(e,0)):n.resolve(e[0])},1)},function(e){n.reject(e)})}).promise()},extend:function(e){var t=f.call(arguments,1);for(var n=0;n<t.length;n++){var r=t[n];if(r)for(var i in r)e[i]=r[i]}return e},wait:function(e){return o.defer(function(t){setTimeout(t.resolve,e)}).promise()}},o.keys=r||function(e){if(e!==Object(e))throw new TypeError("Invalid object");var t=[];for(var n in e)i.call(e,n)&&(t[t.length]=n);return t},o.isElement=function(e){return!!e&&e.nodeType===1},o.isArray=a||function(e){return s.call(e)=="[object Array]"},o.isObject=function(e){return e===Object(e)},o.isBoolean=function(e){return typeof e=="boolean"},o.isPromise=function(e){return e&&o.isFunction(e.then)};var d=["Arguments","Function","String"
,"Number","Date","RegExp"];for(var m=0;m<d.length;m++)v(d[m]);return o});